create table if not exists public.beers (
  "id" integer generated by default as identity primary key,
  "name" text not null,
  "description" text not null,
  "real" boolean not null,
  "createdAt" timestamptz not null default timezone('utc'::text, now())
);

drop table if exists public.game_guesses;
drop table if exists public.games;
drop table if exists public.leaderboard;

create table if not exists public.games (
  "id" integer generated by default as identity primary key,
  "userId" text,
  "playerName" text,
  "score" integer not null check ("score" >= 0),
  "bestStreak" integer not null default 0 check ("bestStreak" >= 0),
  "correctGuesses" integer not null default 0 check ("correctGuesses" >= 0),
  "totalGuesses" integer not null default 0 check ("totalGuesses" >= 0),
  "startingLives" integer not null default 3 check ("startingLives" >= 0),
  "livesRemaining" integer not null check ("livesRemaining" >= 0),
  "endedAt" timestamptz,
  "endReason" text check ("endReason" in ('lives_exhausted', 'abandoned')),
  check ("livesRemaining" <= "startingLives"),
  "createdAt" timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.game_guesses (
  "id" integer generated by default as identity primary key,
  "gameId" integer not null references public.games ("id") on delete cascade,
  "beerId" integer not null references public.beers ("id"),
  "guess" boolean not null,
  "correctAnswer" boolean not null,
  "isCorrect" boolean not null,
  "streakBeforeGuess" integer not null default 0 check ("streakBeforeGuess" >= 0),
  "streakAfterGuess" integer not null default 0 check ("streakAfterGuess" >= 0),
  "pointsAwarded" integer not null default 0 check ("pointsAwarded" >= 0),
  "lifeDelta" integer not null check ("lifeDelta" in (0, -1)),
  "createdAt" timestamptz not null default timezone('utc'::text, now())
);

create index if not exists "games_userId_idx" on public.games ("userId");
create index if not exists "games_score_idx" on public.games ("score" desc);
create index if not exists "games_endedAt_idx" on public.games ("endedAt");
create index if not exists "game_guesses_gameId_idx" on public.game_guesses ("gameId");
create index if not exists "game_guesses_beerId_idx" on public.game_guesses ("beerId");

drop view if exists public.random_beers;

create view public.random_beers as
select
  "createdAt",
  "description",
  "id",
  "name",
  "real"
from public.beers
order by random();
