create table if not exists public.promo_clicks (
  "id" bigint generated by default as identity primary key,
  "promoId" text not null,
  "placement" text not null,
  "kind" text not null,
  "href" text not null,
  "actorId" text,
  "gameId" integer references public.games ("id") on delete set null,
  "createdAt" timestamptz not null default timezone('utc'::text, now())
);

create index if not exists "promo_clicks_promoId_idx"
  on public.promo_clicks ("promoId");

create index if not exists "promo_clicks_placement_idx"
  on public.promo_clicks ("placement");

create index if not exists "promo_clicks_createdAt_idx"
  on public.promo_clicks ("createdAt" desc);

create index if not exists "promo_clicks_gameId_idx"
  on public.promo_clicks ("gameId");
