create table if not exists public.beers (
  "id" integer generated by default as identity primary key,
  "name" text not null,
  "description" text not null,
  "real" boolean not null,
  "createdAt" timestamptz not null default timezone('utc'::text, now())
);

create table if not exists public.leaderboard (
  "id" integer generated by default as identity primary key,
  "userId" text not null unique,
  "name" text not null,
  "score" integer not null check ("score" >= 0),
  "createdAt" timestamptz not null default timezone('utc'::text, now())
);

create or replace view public.random_beers as
select
  "id",
  "name",
  "description",
  "real",
  "createdAt"
from public.beers
order by random();
